ChatAppWithSignalR/Models/ErrorViewModel.cs
using System;

namespace ChatAppWithSignalR.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ChatAppWithSignalR/Controllers/GlobalChatController.cs
using ChatAppWithSignalR.Hubs;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ChatAppWithSignalR.Controllers
{
    public class GlobalChatController : Controller
    {
        private readonly IHubContext<MessageHub> _messageHubContext;

        public GlobalChatController(IHubContext<MessageHub> messageHubContext)
        {
            _messageHubContext = messageHubContext;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Announcement()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Announcement(string message)
        {
            _messageHubContext.Clients.All.SendAsync("ReceiveMessage", message);
            return View();
        }
    }
}

ChatAppWithSignalR/Controllers/HomeController.cs
using ChatAppWithSignalR.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ChatAppWithSignalR.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ChatAppWithSignalR/Views/GlobalChat/Announcement.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<form asp-controller="GlobalChat" asp-action="Announcement">
    <div class="row">
        <div class="col-4">
            <div class="form-group">
                <input class="form-control" name="message" />
            </div>
        </div>

        <div class="col-4">
            <div class="form-group">
                <input value="Send" class="btn btn-success" type="submit" />
            </div>
        </div>
    </div>
</form>




<link rel="stylesheet" src="~/lib/bootstrap/dist/css/bootstrap.css" />

ChatAppWithSignalR/Views/GlobalChat/Index.cshtml
<h1>Chat</h1>

<div class="row">
    <div class="col-3">
        <div class="form-group">
            <select id="group" class="form-control">
                <option value="ToAll">To All</option>
                <option value="ToMySelf">To My Self</option>
                <option value="ToSelectedUser">To Selected User</option>
                <option value="ToJointGroup">To Joint Group</option>
            </select>
        </div>
    </div>

    <div class="col-3">
        <div class="form-group">
            <select id="userConnectionIdDropDown" class="form-control" hidden>
                <option>Select Connection Id</option>
            </select>
        </div>
    </div>

    <div class="col-4">
        <div class="form-group">
            <input id="groupNametxt" placeholder="Group Name" class="form-control" hidden/>
        </div>
    </div>
    <div class="col-2">
        <div class="form-group">
            <button id="joinGroupBtn" class="btn btn-primary" hidden>Join Group</button>
        </div>
    </div>
</div>

<table id="chatTable" class="table table-bordered ">
    <thead>
        <tr>
            <td>
                Sent
            </td>
            <td>
                Receive
            </td>
        </tr>
    </thead>
    <tbody>
        @*<tr><td></td><td></td></tr>*@
    </tbody>
</table>




<div class="row">
    <div class="col-10">
        <div class="form-group">
            <input id="messageInput" class="form-control" />
        </div>
    </div>
    <div class="col-2">
        <div class="form-group">
            <button id="sendBtn" class="btn btn-success col-12">Send</button>
        </div>
    </div>
</div>



@*----------------------------JAVASCRIPT--------------------------------*@
<link rel="stylesheet" src="~/lib/bootstrap/dist/css/bootstrap.css" />
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="~/lib/signalr/dist/browser/signalr.js"></script>

<script>
    //-------------------------------------------------- SignalR Connection Initialization ----------------------------------------------
    let signalRConnection = new signalR.HubConnectionBuilder().withUrl("/message").build();

    signalRConnection.start().catch(function (error) {
        console.warn(error);
    });



    //-------------------------------------------------- SignalR Events Binding ---------------------------------------------------------
    signalRConnection.on("ReceiveMessage", function (message) {
        $('#chatTable tbody').append("<tr><td></td><td>" + message + "</td></tr>");
    });

    signalRConnection.on("UserConnected", function (userConnectionId) {
        $('#userConnectionIdDropDown').append($('<option value=' + userConnectionId + '>' + userConnectionId + '</option>'));
    });

    signalRConnection.on("UserDisconnected", function (userConnectionId) {
        $('#userConnectionIdDropDown option[value=' + userConnectionId + ']').remove();
    });



    //-------------------------------------------------- SignalR Calling Method ---------------------------------------------------------
    function SendMessageToAll(message) {
        signalRConnection.invoke('SendMessageToAll', message).catch(function (error) {
            console.warn(error);
        });
    }

    function SendMessageToCaller(message) {
        signalRConnection.invoke('SendMessageToCaller', message).catch(function (error) {
            console.warn(error);
        });
    }

    function SendMessageToUser(connectionId, message) {
        signalRConnection.invoke('SendMessageToUser', connectionId, message).catch(function (error) {
            console.warn(error);
        });
    }

    function JoinGroup(groupName) {
        signalRConnection.invoke('JoinGroup', groupName).catch(function (error) {
            console.warn(error);
        });
    }

    function SendMessageToGroup(groupName, message) {
        signalRConnection.invoke('SendMessageToGroup', groupName, message).catch(function (error) {
            console.warn(error);
        });
    }



    //-------------------------------------------------- Other DOM Manipulation ------------------------------------------------------------
    $("#sendBtn").click(function () {
        let messageInput = $('#messageInput');
        let sendingMsg = messageInput.val();
        let groupValue = $("#group").val();

        if (groupValue === 'ToAll') {
            SendMessageToAll(sendingMsg);
        }
        else if (groupValue === 'ToMySelf') {
            SendMessageToCaller(sendingMsg)
        }
        else if (groupValue === 'ToSelectedUser') {
            let userConnectionId = $("#userConnectionIdDropDown").val();
            SendMessageToUser(userConnectionId, sendingMsg);
        }
        else if (groupValue === 'ToJointGroup') {
            let groupName = $("#groupNametxt").val();
            SendMessageToGroup(groupName, sendingMsg);
        }

        $('#chatTable tbody').append("<tr><td>" + sendingMsg + "</td><td></td></tr>");

        messageInput.val("");
    });

    $("#group").change(function () {
        let groupDropDownVal = $(this).val();

        if (groupDropDownVal === 'ToSelectedUser') {
            $("#userConnectionIdDropDown").attr('hidden', false);
        }
        else {
            $("#userConnectionIdDropDown").attr('hidden', true);
        }

        if (groupDropDownVal === 'ToJointGroup') {
            $("#groupNametxt").attr('hidden', false);
            $("#joinGroupBtn").attr('hidden', false);
        }
        else {
            $("#groupNametxt").attr('hidden', true);
            $("#joinGroupBtn").attr('hidden', true);
        }
    });

    $('#joinGroupBtn').click(function () {
        let groupName = $('#groupNametxt').val();
        JoinGroup(groupName);
        $('#joinGroupBtn').attr('disabled', true).removeClass('btn-primary').addClass('btn-success');
    });

</script>

ChatAppWithSignalR/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ChatAppWithSignalR/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ChatAppWithSignalR</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ChatAppWithSignalR</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ChatAppWithSignalR - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>